source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"
use_frameworks!

target 'toast-project' do

pod 'Alamofire'
pod 'HanekeSwift'
pod 'CCHLinkTextView'
pod 'FBSDKShareKit'
pod 'ParseFacebookUtilsV4','1.8.5'

end

target 'toast-projectTests' do

end

